version: '3.7'
services:
  postgres_db:
    image: postgres:${POSTGRES_VERSION:-latest}
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=keycloak"
    ports:
      - '5432:5432'
    volumes:
    - "./db.sql:/docker-entrypoint-initdb.d/db.sql"
    - "postgres_storage:/var/lib/postgresql/data/"
    networks:
      - ${GLOBAL_NETWORK:-keycloak}


volumes:
  postgres_storage:
    driver: local

