version: '3.7'
services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    hostname: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - ${GLOBAL_NETWORK:-grafana}
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      - ${GLOBAL_NETWORK:-prometheus}