server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Armando1514/Event-Driven-Microservices.git
          default-label: main
          search-paths: microservices/config-server-repository
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: '1234'

log:
  app-name: config-server

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG